# PUBLIC REPO - FAKE DATA ONLY
---
snmp_communities:
  - secret
  - moresecret
junos_root_password: $6$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
junos_ospf_md5_key: $aaaaaaaaaaaaaaaaaaa
junos_vrrp_key: $aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

users_passwords:
  rancid: $6$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

nokia_users_passwords:
  admin: $y$jaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  linuxadmin: $y$jaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  homer: $y$jaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

nokia_snmp_community: $aesaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

trusted_space4: []
#   - description: text
#     network: 192.0.0.0/24
trusted_space6: []

# Prefixes to ban, v4 and v6 with subnet
# blackhole:
#   - 192.0.0.0/24
#   - 2606:2800:220:1::/64
#
blackhole: []
block80: []
#
