# PUBLIC REPO - FAKE DATA ONLY
---
snmp_communities:
  - secret
  - moresecret
junos_root_password: $aaaaaaaaaaaaaaaaaaaaaaaaaaa
junos_ospf_md5_key: $aaaaaaaaaaaaaaaaaaa
junos_vrrp_key: $aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
